# Generated by Django 6.1 on 2026-09-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_viewsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='background_color',
            field=models.CharField(default='#3b82f6', max_length=7),
        ),
    ]
