# Generated by Django 6.1 on 2026-09-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_tag_background_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stickynote',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='stickynote',
            name='background_color',
        ),
        migrations.AddField(
            model_name='stickynote',
            name='color',
            field=models.CharField(default='#ffeb3b', max_length=7),
        ),
        migrations.AlterField(
            model_name='stickynote',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
