# Generated by Django 6.1 on 2026-09-08 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_stickynote_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_calendar_event',
            field=models.BooleanField(default=False),
        ),
    ]
